# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/josh/Equinox-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/josh/Equinox-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/josh/Equinox-Engine/CMakeFiles /home/josh/Equinox-Engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/josh/Equinox-Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named luajit

# Build rule for target.
luajit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 luajit
.PHONY : luajit

# fast build rule for target.
luajit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/luajit.dir/build.make CMakeFiles/luajit.dir/build
.PHONY : luajit/fast

#=============================================================================
# Target rules for targets named rbgccxml

# Build rule for target.
rbgccxml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rbgccxml
.PHONY : rbgccxml

# fast build rule for target.
rbgccxml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rbgccxml.dir/build.make CMakeFiles/rbgccxml.dir/build
.PHONY : rbgccxml/fast

#=============================================================================
# Target rules for targets named bindings

# Build rule for target.
bindings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bindings
.PHONY : bindings

# fast build rule for target.
bindings/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bindings.dir/build.make CMakeFiles/bindings.dir/build
.PHONY : bindings/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

#=============================================================================
# Target rules for targets named equinox

# Build rule for target.
equinox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 equinox
.PHONY : equinox

# fast build rule for target.
equinox/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/build
.PHONY : equinox/fast

api.o: api.cpp.o
.PHONY : api.o

# target to build an object file
api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/api.cpp.o
.PHONY : api.cpp.o

api.i: api.cpp.i
.PHONY : api.i

# target to preprocess a source file
api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/api.cpp.i
.PHONY : api.cpp.i

api.s: api.cpp.s
.PHONY : api.s

# target to generate assembly for a file
api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/api.cpp.s
.PHONY : api.cpp.s

engine.o: engine.cpp.o
.PHONY : engine.o

# target to build an object file
engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/engine.cpp.o
.PHONY : engine.cpp.o

engine.i: engine.cpp.i
.PHONY : engine.i

# target to preprocess a source file
engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/engine.cpp.i
.PHONY : engine.cpp.i

engine.s: engine.cpp.s
.PHONY : engine.s

# target to generate assembly for a file
engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/engine.cpp.s
.PHONY : engine.cpp.s

entity.o: entity.cpp.o
.PHONY : entity.o

# target to build an object file
entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/entity.cpp.o
.PHONY : entity.cpp.o

entity.i: entity.cpp.i
.PHONY : entity.i

# target to preprocess a source file
entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/entity.cpp.i
.PHONY : entity.cpp.i

entity.s: entity.cpp.s
.PHONY : entity.s

# target to generate assembly for a file
entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/entity.cpp.s
.PHONY : entity.cpp.s

entry.o: entry.cpp.o
.PHONY : entry.o

# target to build an object file
entry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/entry.cpp.o
.PHONY : entry.cpp.o

entry.i: entry.cpp.i
.PHONY : entry.i

# target to preprocess a source file
entry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/entry.cpp.i
.PHONY : entry.cpp.i

entry.s: entry.cpp.s
.PHONY : entry.s

# target to generate assembly for a file
entry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/entry.cpp.s
.PHONY : entry.cpp.s

gui.o: gui.cpp.o
.PHONY : gui.o

# target to build an object file
gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/gui.cpp.o
.PHONY : gui.cpp.o

gui.i: gui.cpp.i
.PHONY : gui.i

# target to preprocess a source file
gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/gui.cpp.i
.PHONY : gui.cpp.i

gui.s: gui.cpp.s
.PHONY : gui.s

# target to generate assembly for a file
gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/gui.cpp.s
.PHONY : gui.cpp.s

instance.o: instance.cpp.o
.PHONY : instance.o

# target to build an object file
instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/instance.cpp.o
.PHONY : instance.cpp.o

instance.i: instance.cpp.i
.PHONY : instance.i

# target to preprocess a source file
instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/instance.cpp.i
.PHONY : instance.cpp.i

instance.s: instance.cpp.s
.PHONY : instance.s

# target to generate assembly for a file
instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/instance.cpp.s
.PHONY : instance.cpp.s

lua/bindings.o: lua/bindings.cpp.o
.PHONY : lua/bindings.o

# target to build an object file
lua/bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/lua/bindings.cpp.o
.PHONY : lua/bindings.cpp.o

lua/bindings.i: lua/bindings.cpp.i
.PHONY : lua/bindings.i

# target to preprocess a source file
lua/bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/lua/bindings.cpp.i
.PHONY : lua/bindings.cpp.i

lua/bindings.s: lua/bindings.cpp.s
.PHONY : lua/bindings.s

# target to generate assembly for a file
lua/bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/lua/bindings.cpp.s
.PHONY : lua/bindings.cpp.s

lua_wrapper.o: lua_wrapper.cpp.o
.PHONY : lua_wrapper.o

# target to build an object file
lua_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/lua_wrapper.cpp.o
.PHONY : lua_wrapper.cpp.o

lua_wrapper.i: lua_wrapper.cpp.i
.PHONY : lua_wrapper.i

# target to preprocess a source file
lua_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/lua_wrapper.cpp.i
.PHONY : lua_wrapper.cpp.i

lua_wrapper.s: lua_wrapper.cpp.s
.PHONY : lua_wrapper.s

# target to generate assembly for a file
lua_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/lua_wrapper.cpp.s
.PHONY : lua_wrapper.cpp.s

net.o: net.cpp.o
.PHONY : net.o

# target to build an object file
net.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/net.cpp.o
.PHONY : net.cpp.o

net.i: net.cpp.i
.PHONY : net.i

# target to preprocess a source file
net.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/net.cpp.i
.PHONY : net.cpp.i

net.s: net.cpp.s
.PHONY : net.s

# target to generate assembly for a file
net.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/net.cpp.s
.PHONY : net.cpp.s

scene.o: scene.cpp.o
.PHONY : scene.o

# target to build an object file
scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/scene.cpp.o
.PHONY : scene.cpp.o

scene.i: scene.cpp.i
.PHONY : scene.i

# target to preprocess a source file
scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/scene.cpp.i
.PHONY : scene.cpp.i

scene.s: scene.cpp.s
.PHONY : scene.s

# target to generate assembly for a file
scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/scene.cpp.s
.PHONY : scene.cpp.s

server.o: server.cpp.o
.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i
.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s
.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/server.cpp.s
.PHONY : server.cpp.s

sound.o: sound.cpp.o
.PHONY : sound.o

# target to build an object file
sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/sound.cpp.o
.PHONY : sound.cpp.o

sound.i: sound.cpp.i
.PHONY : sound.i

# target to preprocess a source file
sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/sound.cpp.i
.PHONY : sound.cpp.i

sound.s: sound.cpp.s
.PHONY : sound.s

# target to generate assembly for a file
sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/sound.cpp.s
.PHONY : sound.cpp.s

state.o: state.cpp.o
.PHONY : state.o

# target to build an object file
state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/state.cpp.o
.PHONY : state.cpp.o

state.i: state.cpp.i
.PHONY : state.i

# target to preprocess a source file
state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/state.cpp.i
.PHONY : state.cpp.i

state.s: state.cpp.s
.PHONY : state.s

# target to generate assembly for a file
state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/state.cpp.s
.PHONY : state.cpp.s

team.o: team.cpp.o
.PHONY : team.o

# target to build an object file
team.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/team.cpp.o
.PHONY : team.cpp.o

team.i: team.cpp.i
.PHONY : team.i

# target to preprocess a source file
team.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/team.cpp.i
.PHONY : team.cpp.i

team.s: team.cpp.s
.PHONY : team.s

# target to generate assembly for a file
team.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/team.cpp.s
.PHONY : team.cpp.s

unit_ai.o: unit_ai.cpp.o
.PHONY : unit_ai.o

# target to build an object file
unit_ai.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/unit_ai.cpp.o
.PHONY : unit_ai.cpp.o

unit_ai.i: unit_ai.cpp.i
.PHONY : unit_ai.i

# target to preprocess a source file
unit_ai.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/unit_ai.cpp.i
.PHONY : unit_ai.cpp.i

unit_ai.s: unit_ai.cpp.s
.PHONY : unit_ai.s

# target to generate assembly for a file
unit_ai.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/unit_ai.cpp.s
.PHONY : unit_ai.cpp.s

weapon.o: weapon.cpp.o
.PHONY : weapon.o

# target to build an object file
weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/weapon.cpp.o
.PHONY : weapon.cpp.o

weapon.i: weapon.cpp.i
.PHONY : weapon.i

# target to preprocess a source file
weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/weapon.cpp.i
.PHONY : weapon.cpp.i

weapon.s: weapon.cpp.s
.PHONY : weapon.s

# target to generate assembly for a file
weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/equinox.dir/build.make CMakeFiles/equinox.dir/weapon.cpp.s
.PHONY : weapon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bindings"
	@echo "... luajit"
	@echo "... rbgccxml"
	@echo "... shaders"
	@echo "... equinox"
	@echo "... api.o"
	@echo "... api.i"
	@echo "... api.s"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... entity.o"
	@echo "... entity.i"
	@echo "... entity.s"
	@echo "... entry.o"
	@echo "... entry.i"
	@echo "... entry.s"
	@echo "... gui.o"
	@echo "... gui.i"
	@echo "... gui.s"
	@echo "... instance.o"
	@echo "... instance.i"
	@echo "... instance.s"
	@echo "... lua/bindings.o"
	@echo "... lua/bindings.i"
	@echo "... lua/bindings.s"
	@echo "... lua_wrapper.o"
	@echo "... lua_wrapper.i"
	@echo "... lua_wrapper.s"
	@echo "... net.o"
	@echo "... net.i"
	@echo "... net.s"
	@echo "... scene.o"
	@echo "... scene.i"
	@echo "... scene.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... sound.o"
	@echo "... sound.i"
	@echo "... sound.s"
	@echo "... state.o"
	@echo "... state.i"
	@echo "... state.s"
	@echo "... team.o"
	@echo "... team.i"
	@echo "... team.s"
	@echo "... unit_ai.o"
	@echo "... unit_ai.i"
	@echo "... unit_ai.s"
	@echo "... weapon.o"
	@echo "... weapon.i"
	@echo "... weapon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

